version: 1
formatters:
  simple:
    format: "%(asctime)s | %(levelname)-7s | %(name)s:%(lineno)d | %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: logs/app.log
    mode: "a"
    encoding: utf-8
loggers:
  __main__:
    level: DEBUG
    handlers: [console, file]
  mastodon_bot:
    level: DEBUG
    handlers: [console, file]
