version: 1
formatters:
  simple:
    format: "%(asctime)s | %(levelname)-7s | %(name)s:%(lineno)d | %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  __main__:
    level: DEBUG
    handlers: [console]
  mastodon_bot:
    level: DEBUG
    handlers: [console]
